name: act

params:
  exec_horizon: 2
  act_config:
    lr_backbone: 1.0e-05
    kl_weight: 10.0
    backbone: resnet18
    dilation: false
    position_embedding: sine
    enc_layers: 4
    dec_layers: 6
    dim_feedforward: 2048
    hidden_dim: 256
    dropout: 0.1
    nheads: 8
    pre_norm: false
    masks: false
