# Test on train: rollout using init states from the demo HDF5.
ckpt: "standalone/standalone_runs/train_cnnmlp_quickcheck/run_000/model_last.pt"
use_ckpt_config: true
init_states: null

steps: 1000
sample_index: 0
n_rollouts: 90
warmup_steps: 10
use_mp: true
num_procs: 10

save_videos: 90
video_camera: "agentview_rgb,eye_in_hand_rgb"
video_fps: 30
video_dir: "standalone/standalone_runs/train_cnnmlp_quickcheck/run_000/rollout_on_train_init"

device: "cuda:0"
