data:
  demo_file: ./libero/datasets/libero_object_single/pick_up_the_alphabet_soup_and_place_it_in_the_basket_demo.hdf5
  obs_keys: "joint_states,gripper_states"
  image_keys: "agentview_rgb,eye_in_hand_rgb"
  obs_horizon: 8
  predict_horizon: 4
  normalize_obs: false
  obs_stats_path: null
  seed: 10000
policy:
  config_path: standalone/configs/policies/cnnmlp.yaml
ckpt: "standalone/standalone_runs/run_001/model_last.pt"
init_states: ""
steps: 8
sample_index: 0
n_eval: 1
use_mp: false
num_procs: 1
warmup_steps: 5
save_videos: 0
video_camera: ""
video_fps: 30
video_dir: ""
device: "cuda:0"
