# Test on test: rollout using init states from init_files (pruned_init).
ckpt: "standalone/standalone_runs/train_cnnmlp_quickcheck/run_000/model_last.pt"
use_ckpt_config: true
init_states: "./libero/libero/init_files/libero_object_single/pick_up_the_alphabet_soup_and_place_it_in_the_basket.pruned_init"

steps: 1000
sample_index: 0
n_rollouts: 90
warmup_steps: 10
use_mp: true
num_procs: 10

save_videos: 90
video_camera: "agentview_rgb,eye_in_hand_rgb"
video_fps: 30
video_dir: "standalone/standalone_runs/train_cnnmlp_quickcheck/run_000/rollout_on_test_init"

device: "cuda:0"
