ckpt: "standalone/standalone_runs/train_cnnmlp_quickcheck/run_000/model_last.pt"
use_ckpt_config: true
init_states: null

steps: 1000
sample_index: 0
n_rollouts: 5
warmup_steps: 10
use_mp: false
num_procs: 1

save_videos: 5
video_camera: "agentview_rgb"
video_fps: 30
video_dir: "standalone/standalone_runs/train_cnnmlp_quickcheck/run_000/rollout_example"

device: "cuda:0"
