data:
  demo_file: ./libero/datasets/libero_object_single/pick_up_the_alphabet_soup_and_place_it_in_the_basket_demo.hdf5
  obs_keys: "joint_states,gripper_states"
  image_keys: "agentview_rgb,eye_in_hand_rgb"
  obs_horizon: 8
  predict_horizon: 4
  normalize_obs: false
  obs_stats_path: null
  train_ratio: 0.9
  val_ratio: 0.1
  seed: 10000

policy: {}

paths:
  save_dir: "standalone/standalone_runs/run_001"

training:
  batch_size: 2
  epochs: 1
  val_every: 10
  lr: 0.0001
  grad_clip: 100.0
  device: "cuda:0"

rollout:
  every: 20
  init_states_dir: null
  env_horizon: 2000
  per_anchor: 2
  steps: 8
  warmup_steps: 5
  use_mp: false
  num_procs: 1

logging:
  use_wandb: false
  wandb_project: "libero-standalone"
  wandb_entity: null
  experiment_name: null
