data:
  demo_file: ./libero/datasets/libero_object_single/pick_up_the_alphabet_soup_and_place_it_in_the_basket_demo.hdf5
  obs_keys: "joint_states,gripper_states,ee_pos"
  image_keys: "agentview_rgb,eye_in_hand_rgb"
  obs_horizon: 1
  predict_horizon: 1
  action_shift: 1  # Predict next-step actions from current obs.
  normalize_obs: false
  obs_stats_path: null
  obs_key_mapping:
    ee_pos: robot0_eef_pos
  train_ratio: 0.9
  val_ratio: 0.1
  seed: 10000
policy:
  config_path: standalone/configs/policies/cnnmlp.yaml
  params:
    exec_horizon: 1
    act_config:
      backbone: resnet18
      lr_backbone: 1.0e-05
      image_norm: imagenet
      hidden_dim: 256
      position_embedding: sine
      dilation: false
      masks: false
batch_size: 512
epochs: 50
val_every: 10
rollout_every: 10
rollout_init_states_dir: ./libero/libero/init_files/
rollout_per_anchor: 2
rollout_steps: 1000
rollout_warmup_steps: 10
rollout_use_mp: true
rollout_num_procs: 9
lr: 0.0001
device: "cuda:0"
save_dir: "standalone/standalone_runs/run_cnnmlp_quickcheck"
grad_clip: null
use_wandb: true
wandb_project: "libero-standalone"
wandb_entity: null
experiment_name: train_cnnmlp_quickcheck
